In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import root_mean_squared_error, r2_score


df_train = pd.read_csv("./src/data/train.csv")
df_test = pd.read_csv("./src/data/test.csv")

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10517 entries, 0 to 10516
Columns: 1078 entries, LogP to mZagreb2
dtypes: float64(1078)
memory usage: 86.5 MB

In [ ]:
df_train.columns

Index(['LogP', 'nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDiam_A', 'SpAD_A',
       'SpMAD_A', 'LogEE_A', 'VE1_A',
       ...
       'SRW10', 'TSRW10', 'MW', 'AMW', 'WPath', 'WPol', 'Zagreb1', 'Zagreb2',
       'mZagreb1', 'mZagreb2'],
      dtype='object', length=1078)

In [ ]:


df_train = pd.read_csv("./src/data/train.csv")
df_test = pd.read_csv("./src/data/test.csv")


X = df_train.drop(columns="LogP")
y = df_train["LogP"]


model = RandomForestRegressor(n_estimators=100, max_depth=10,
                                      min_samples_split=2, random_state=42)
model.fit(X, y)
y_pred = model.predict(X)
r_squared = r2_score(y, y_pred)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred)}")

print("===================================")

X = df_test.drop(columns="LogP")
y = df_test["LogP"]

y_pred_test = model.predict(X)
r_squared = r2_score(y, y_pred_test)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred_test)}")

training r_squared score :
0.3253868966553102
RMSE : 1.4986893208668148
===================================
training r_squared score :
0.288561453864436
RMSE : 1.5457920541197498

In [ ]:
import pandas as pd
df = pd.read_csv("./trash/data/sample.csv")

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
df = df.drop(columns=df.select_dtypes(include=["object"]).columns)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10527 entries, 0 to 10526
Columns: 1079 entries, nAcid to mZagreb2
dtypes: bool(2), float64(768), int64(309)
memory usage: 86.5 MB

In [ ]:
target = pd.read_csv("./trash/data/TR_LogP_10537.csv")
y = target['LogP']

In [ ]:
y.shape

(10537,)

In [ ]:
target.head()

,ChemID,source_casrn,CAS,SMILES,NAME,preferred_name,iupac,MPID,dsstox_substance_id,Canonical_QSARr,InChI_Code_QSARr,InChI Key_QSARr,Salt_Solvent,Salt_Solvent_ID,Kow Reference,LogP
0,100001,50-00-0,50-00-0,[H]C([H])=O,FORMALDEHYDE,Formaldehyde,formaldehyde,4675,DTXSID7020637,C=O,InChI=1S/CH2O/c1-2/h1H2,WSFSSNUMVMOOMR-UHFFFAOYSA-N,?,NaN,"HANSCH,C ET AL. (1995)",0.35
1,100002,50-02-2|378-44-9,50-02-2|378-44-9,[H]OC([H])([H])C(=O)C1(O[H])C([H])(C([H])([H])...,"DEXAMETHASONE, BETAMETHASONE",Dexamethasone,"(11beta,16alpha)-9-fluoro-11,17,21-trihydroxy-...",4676|6480,DTXSID3020384|DTXSID3022667,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,InChI=1S/C22H29FO5/c1-12-8-16-15-5-4-13-9-14(2...,UREBDLICKHMUKA-UHFFFAOYSA-N,?,NaN,"HANSCH,C ET AL. (1995)",1.83
2,100003,50-03-3,50-03-3,[H]OC1([H])C([H])([H])C2(C([H])([H])[H])C(O[H]...,HYDROCORTISONE ACETATE,Hydrocortisone acetate,"(8xi,9xi,11beta,14xi)-11,17-dihydroxy-3,20-dio...",4677,DTXSID0048686,CC(=O)OCC(=O)C1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3C(...,InChI=1S/C23H32O6/c1-13(24)29-12-19(27)23(28)9...,ALEXXDVDDISNDU-UHFFFAOYSA-N,?,NaN,"HANSCH,C ET AL. (1995)",2.19
3,100005,50-06-6,50-06-6,[H]C1=C([H])C([H])=C(C2(C([H])([H])C([H])([H])...,PHENOBARBITAL,Phenobarbital,"5-ethyl-5-phenylpyrimidine-2,4,6(1H,3H,5H)-trione",4679,DTXSID5021122,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O,InChI=1S/C12H12N2O3/c1-2-12(8-6-4-3-5-7-8)9(15...,DDBREPKUVSBGFI-UHFFFAOYSA-N,?,NaN,"HANSCH,C ET AL. (1995)",1.47
4,100006,50-07-7,50-07-7,[H]N([H])C(=O)OC([H])([H])C1([H])C2=C(C(=O)C(C...,MITOMYCIN C,Mitomycin C,"[(1aS,8S,8aR,8bS)-6-amino-8a-methoxy-5-methyl-...",4680,DTXSID2020898,CC1C(=O)C2=C(C(COC(N)=O)C3(OC)C4NC4CN32)C(=O)C=1N,InChI=1S/C15H18N4O5/c1-5-9(16)12(21)8-6(4-24-1...,NWIBSHFKIJFRCO-UHFFFAOYSA-N,?,NaN,"HANSCH,C ET AL. (1995)",-0.40

In [ ]:
df_train = pd.read_csv("./trash/data/train_new.csv")

In [ ]:
df_train = df_train.drop(columns="ChemID")

In [ ]:
df_test = pd.read_csv("./src/data/test.csv")
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3511 entries, 0 to 3510
Columns: 1078 entries, LogP to mZagreb2
dtypes: float64(1078)
memory usage: 28.9 MB

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error, r2_score

df_train = pd.read_csv("./trash/data/train_new.csv")
df_train = df_train.drop(columns="ChemID")
# df_train = pd.read_csv("./trash/data/train_new.csv")
# df_test = pd.read_csv("./src/data/test.csv")


X = df_train.drop(columns="LogP")
y = df_train["LogP"]


model = RandomForestRegressor(n_estimators=100, max_depth=10,
                                      min_samples_split=2, random_state=42)
model.fit(X, y)
y_pred = model.predict(X)
r_squared = r2_score(y, y_pred)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred)}")

print("===================================")

# X = df_test.drop(columns="LogP")
# y = df_test["LogP"]

# y_pred_test = model.predict(X)
# r_squared = r2_score(y, y_pred_test)
# print("training r_squared score : ")
# print(r_squared)
# print(f"RMSE : {root_mean_squared_error(y, y_pred_test)}")

training r_squared score :
0.3485813965264063
RMSE : 1.4727000618022463
===================================

In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error, r2_score
import pandas as pd

df_train = pd.read_csv("./trash/data/train_new.csv")
df_train = df_train.drop(columns="ChemID")
# df_train = pd.read_csv("./trash/data/train_new.csv")
# df_test = pd.read_csv("./src/data/test.csv")


X = df_train.drop(columns="LogP")
y = df_train["LogP"]

X = X[["MW", "nHBDon", "nHBAcc", "nRing", "TopoPSA(NO)", "nAromAtom", "Zagreb1", "SLogP", "BalabanJ", "Kier1"]]

:

In [ ]:

model = RandomForestRegressor(n_estimators=1000, max_depth=None,
                                      min_samples_split=3, random_state=42)
model.fit(X, y)

RandomForestRegressor(min_samples_split=3, n_estimators=1000, random_state=42)

In [ ]:
y_pred = model.predict(X)
r_squared = r2_score(y, y_pred)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred)}")

print("===================================")

training r_squared score :
0.9328250447215275
RMSE : 0.47499175118865106
===================================

In [ ]:
df_test = pd.read_csv("./trash/data/test_new.csv")
df_test.info()

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x7efe1285b4f0>>
Traceback (most recent call last):
  File "/home/junsoo/miniconda3/envs/mordred/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 781, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(
KeyboardInterrupt:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3511 entries, 0 to 3510
Columns: 1082 entries, Unnamed: 0 to mZagreb2
dtypes: bool(2), float64(769), int64(311)
memory usage: 28.9 MB

In [ ]:
df_test.head()

,Unnamed: 0,LogP,ChemID,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,0,2.10,100004,0,0,36.259361,2.671204,5.283132,36.259361,1.250323,...,10.840071,80.496311,402.204239,6.817021,2039,62,168.0,212.0,11.576389,6.020833
1,1,1.69,100008,0,0,20.636226,2.529728,4.927959,20.636226,1.289764,...,9.904737,63.570655,218.105528,7.270184,390,28,84.0,103.0,6.256944,3.638889
2,2,1.61,100012,0,0,33.006887,2.670617,5.282175,33.006887,1.269496,...,10.812331,77.185478,362.209324,6.468024,1425,59,154.0,198.0,10.215278,5.437500
3,3,6.91,100016,0,0,23.128032,2.424173,4.848346,23.128032,1.217265,...,9.861675,52.418777,351.914689,12.568382,678,28,98.0,112.0,7.618056,4.055556
4,4,0.33,100020,0,0,24.613685,2.527110,4.889102,24.613685,1.295457,...,10.049880,67.510292,258.064057,8.898761,643,33,104.0,127.0,6.638889,4.111111

In [ ]:
df_test = pd.read_csv("./src/data/test.csv")
X = df_test.drop(columns="LogP")
X = X[["MW", "nHBDon", "nHBAcc", "nRing", "TopoPSA(NO)", "nAromAtom", "Zagreb1", "SLogP", "BalabanJ", "Kier1"]]
y = df_test["LogP"]

y_pred_test = model.predict(X)
r_squared = r2_score(y, y_pred_test)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred_test)}")

training r_squared score :
0.18423331721000424
RMSE : 1.655256708486336

In [ ]:
X = df_test.drop(columns="LogP")
X = X[["MW", "nHBDon", "nHBAcc", "nRing", "TopoPSA(NO)", "nAromAtom", "Zagreb1", "SLogP", "BalabanJ", "Kier1"]]
y = df_test["LogP"]

y_pred_test = model.predict(X)
r_squared = r2_score(y, y_pred_test)
print("training r_squared score : ")
print(r_squared)
print(f"RMSE : {root_mean_squared_error(y, y_pred_test)}")

NameError: name 'df_test' is not defined